# **Algorithms associated with Graph Data Structures**

## **Two representations for graphs**

### **Adjacency List**

In the adjacency list representation, we use a dictionary to store the vertices as keys and their corresponding adjacent vertices as values in a list.

In [24]:
# Adjacency List Representation
graph = {
    'A': ['B', 'C'],
    'B': ['A', 'D', 'E'],
    'C': ['A', 'F'],
    'D': ['B'],
    'E': ['B', 'F'],
    'F': ['C', 'E']
}

### **Adjacency Matrix**

In the adjacency matrix representation, we use a 2D matrix to represent the edges between vertices. Each cell (i, j) in the matrix represents an edge between vertex i and vertex j.

In [25]:
# Adjacency Matrix Representation
graph = [
    [0, 1, 1, 0, 0, 0],
    [1, 0, 0, 1, 1, 0],
    [1, 0, 0, 0, 0, 1],
    [0, 1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 1],
    [0, 0, 1, 0, 1, 0]
]

## **1. Create a Graph**

### **1.1. Using Adjacency List**

In [26]:
def add_edge_list(graph, u, v):
    if u not in graph:
        graph[u] = []
    if v not in graph:
        graph[v] = []
    graph[u].append(v)
    graph[v].append(u)


In [27]:
# Graph using Adjacency List
graph_list = {}

# Adding edges to the graph
add_edge_list(graph_list, 'A', 'B')
add_edge_list(graph_list, 'A', 'C')
add_edge_list(graph_list, 'B', 'D')
add_edge_list(graph_list, 'B', 'E')
add_edge_list(graph_list, 'C', 'F')

# print
print(graph_list)

{'A': ['B', 'C'], 'B': ['A', 'D', 'E'], 'C': ['A', 'F'], 'D': ['B'], 'E': ['B'], 'F': ['C']}


### **1.2. Using Adjacency Matrix**

In [28]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [29]:
import numpy as np

In [30]:
def initialize_matrix(graph, num_vertices):
    for _ in range(num_vertices):
        graph.append([0] * num_vertices)

def add_edge_matrix(graph, u, v):
    graph[u][v] = 1
    graph[v][u] = 1

def print_graph_matrix(graph):
    print(np.array(graph))

In [31]:
# Graph using Adjacency Matrix
graph_matrix = []

# Initializing the matrix
initialize_matrix(graph_matrix, 6)

# Adding edges to the graph
add_edge_matrix(graph_matrix, 0, 1)
add_edge_matrix(graph_matrix, 0, 2)
add_edge_matrix(graph_matrix, 1, 3)
add_edge_matrix(graph_matrix, 1, 4)
add_edge_matrix(graph_matrix, 2, 5)

# print
print_graph_matrix(graph_matrix)

[[0 1 1 0 0 0]
 [1 0 0 1 1 0]
 [1 0 0 0 0 1]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]]


### **1.2. Time complexity**



## **2. Depth-First Search (DFS) algorithm**

Depth-First Search (DFS) is an algorithm that explores a graph by traversing as far as possible along each branch before backtracking.

### **2.1. Using Adjancency List**

In [32]:
def dfs_adjacency_list(graph, start, visited):
    visited.add(start)
    print(start, end=" ")

    for neighbor in graph[start]:
        if neighbor not in visited:
            dfs_adjacency_list(graph, neighbor, visited)

In [33]:
# usage
# Create a graph using Adjacency List
graph_list = {}

# Adding edges to the graph
add_edge_list(graph_list, 'A', 'B')
add_edge_list(graph_list, 'A', 'C')
add_edge_list(graph_list, 'B', 'D')
add_edge_list(graph_list, 'B', 'E')
add_edge_list(graph_list, 'C', 'F')

visited = set()
dfs_adjacency_list(graph_list, 'A', visited)

A B D E C F 

### **2.2. Using Adjancency Matrix**

In [34]:
def dfs_adjacency_matrix(graph, start, visited):
    visited.add(start)
    print(start, end=" ")

    for neighbor in range(len(graph[start])):
        if graph[start][neighbor] == 1 and neighbor not in visited:
            dfs_adjacency_matrix(graph, neighbor, visited)


In [35]:
# Usage
# Create a graph using Adjacency Matrix
graph_matrix = []

# Initializing the matrix
initialize_matrix(graph_matrix, 6)

# Adding edges to the graph
add_edge_matrix(graph_matrix, 0, 1)
add_edge_matrix(graph_matrix, 0, 2)
add_edge_matrix(graph_matrix, 1, 3)
add_edge_matrix(graph_matrix, 1, 4)
add_edge_matrix(graph_matrix, 2, 5)

visited = set()
dfs_adjacency_matrix(graph_matrix, 0, visited)

0 1 3 4 2 5 

## **3. Breadth-First Search (BFS) algorithm**

Breadth-First Search (BFS) is an algorithm that explores a graph by traversing all vertices at the same level before visiting the next level.

### **3.1. Using Adjancency List**

In [36]:
from collections import deque

def bfs_adjacency_list(graph, start, visited):
    queue = deque([start])
    visited.add(start)

    while queue:
        vertex = queue.popleft()
        print(vertex, end=" ")

        for neighbor in graph[vertex]:
            if neighbor not in visited:
                visited.add(neighbor)
                queue.append(neighbor)


In [38]:
# Usage
# Create a graph using Adjacency List
graph_list = {}

# Adding edges to the graph
add_edge_list(graph_list, 'A', 'B')
add_edge_list(graph_list, 'A', 'C')
add_edge_list(graph_list, 'B', 'D')
add_edge_list(graph_list, 'B', 'E')
add_edge_list(graph_list, 'C', 'F')

visited = set()
bfs_adjacency_list(graph_list, 'A', visited)

A B C D E F 

### **3.12. Using Adjancency Matrix**

In [39]:
from collections import deque

def bfs_adjacency_matrix(graph, start, visited):
    queue = deque([start])
    visited.add(start)

    while queue:
        vertex = queue.popleft()
        print(vertex, end=" ")

        for neighbor in range(len(graph[vertex])):
            if graph[vertex][neighbor] == 1 and neighbor not in visited:
                visited.add(neighbor)
                queue.append(neighbor)


In [40]:
# Usage
# Create a graph using Adjacency Matrix
graph_matrix = []

# Initializing the matrix
initialize_matrix(graph_matrix, 6)

# Adding edges to the graph
add_edge_matrix(graph_matrix, 0, 1)
add_edge_matrix(graph_matrix, 0, 2)
add_edge_matrix(graph_matrix, 1, 3)
add_edge_matrix(graph_matrix, 1, 4)
add_edge_matrix(graph_matrix, 2, 5)

visited = set()
bfs_adjacency_matrix(graph_matrix, 0, visited)

0 1 2 3 4 5 